# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Top Gun Robotics
email: webmaster@team1294.org
description: > # this means to ignore newlines until "baseurl:"
  Top Gun Robotics, FIRST Robotics Team 1294, is a high school robotics team
  from Eastlake High School in Sammamish, WA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: topgunrobotics
twitter_username: TopGun1294
github_username:  FRC-1294

# Build settings
markdown: kramdown
exclude:
  - .gitignore
  - .stylelintrc
  - .travis.yml
  - .vscode
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - README.md
  - vendor
include:
  - _pages
sass:
  style: compressed
plugins:
  - octopress-autoprefixer
